repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.4b0
    hooks:
      - id: black
        args: ["--line-length=119"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
        exclude: ^data/
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
