name: ci

on:
  pull_request:
  push:
    branches: [master, stage]

jobs:
  pre-commit-pytests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2.1.3

      - name: pre-commit-action
        uses: pre-commit/action@v2.0.0

      - name: run tests
        run: |
          pip install pytest
          python -m pytest tests/ -v
